const quotes = [
"Believe you can and you're halfway there.",
"Do something today that your future self will thank you for.",
"Push yourself because no one else is going to do it for you.",
"Great things never come from comfort zones.",
"Dream it. Wish it. Do it.",
"Success doesn't just find you. You have to go out and get it.",
"The harder you work for something, the greater you'll feel when you achieve it.",
"Dream bigger. Do bigger.",
"Don't stop when you're tired. Stop when you're done.",
"Wake up with determination. Go to bed with satisfaction.",
"Do something today that your future self will thank you for.",
"Little things make big days.",
"It's going to be hard, but hard does not mean impossible.",
"Don't wait for opportunity. Create it.",
"Sometimes later becomes never. Do it now.",
"Great things take time.",
"Don't limit your challenges. Challenge your limits.",
"Stay focused and never give up.",
"Small progress is still progress.",
"Success is the sum of small efforts repeated daily.",
"Work hard in silence, let success make the noise.",
"Believe in yourself and all that you are.",
"You are stronger than you think.",
"Start where you are. Use what you have. Do what you can.",
"The best way to get started is to quit talking and begin doing.",
"Don't be afraid to fail. Be afraid not to try.",
"Success is not for the lazy.",
"Discipline is the bridge between goals and accomplishment.",
"If you can dream it, you can do it.",
"Action is the foundational key to success.",
"Every day is a new opportunity.",
"Make today count.",
"Your limitation—it's only your imagination.",
"Push harder than yesterday.",
"Don't wish for it. Work for it.",
"Stay hungry. Stay foolish.",
"Success usually comes to those who are too busy to be looking for it.",
"The future depends on what you do today.",
"Opportunities don't happen. You create them.",
"Failure is the opportunity to begin again more intelligently.",
"Motivation gets you started. Habit keeps you going.",
"The secret of getting ahead is getting started.",
"Don't stop until you're proud.",
"Hard work beats talent when talent doesn't work hard.",
"Believe in your infinite potential.",
"The difference between ordinary and extraordinary is that little extra.",
"Everything you can imagine is real.",
"Your only limit is your mind.",
"Make each day your masterpiece.",
"Turn your wounds into wisdom.",
"The best view comes after the hardest climb.",
"Dream big and dare to fail.",
"Keep going. Everything you need will come to you.",
"You don't have to be perfect to be amazing.",
"Don't be busy, be productive.",
"The key to success is to focus on goals, not obstacles.",
"Be stronger than your excuses.",
"Success starts with self-discipline.",
"Don't quit. Suffer now and live the rest of your life as a champion.",
"Do what you can with what you have where you are.",
"The harder the battle, the sweeter the victory.",
"Success is not final, failure is not fatal.",
"Your life does not get better by chance, it gets better by change.",
"Work until your idols become your rivals.",
"Focus on progress, not perfection.",
"Make your dreams happen.",
"Success is a journey, not a destination.",
"If you want it, work for it.",
"Believe in the power of yet.",
"Stay positive, work hard, make it happen.",
"Never stop learning.",
"The best investment you can make is in yourself.",
"Consistency is what transforms average into excellence.",
"Progress, not perfection.",
"Be fearless in the pursuit of what sets your soul on fire.",
"Learn from yesterday, live for today, hope for tomorrow.",
"The only place where success comes before work is in the dictionary.",
"Don't watch the clock; do what it does. Keep going.",
"Success is liking yourself, liking what you do, and liking how you do it.",
"Believe you deserve it and the universe will serve it.",
"Be the energy you want to attract.",
"Everything begins with a decision.",
"Dream without fear. Love without limits.",
"Turn your dreams into plans.",
"Make yourself proud.",
"Don't downgrade your dream just to fit your reality.",
"If it doesn't challenge you, it won't change you.",
"Go the extra mile. It's never crowded.",
"Don't be afraid of giving up the good to go for the great.",
"Stay patient and trust your journey.",
"One day or day one. You decide.",
"Strive for progress, not perfection.",
"Success is built on daily habits.",
"The pain you feel today will be the strength you feel tomorrow.",
"Be so good they can't ignore you.",
"Keep moving forward.",
"Greatness takes time."
];


let btn=document.querySelector("button");
let h1=document.querySelector("h1");
btn.addEventListener("click",()=>{
    let idx=Math.floor(Math.random()*100);
    h1.innerText=quotes[idx];
});
